server:
  port: 8080

topic:
  podMsgTopic : podMsgTopic
  delpoyMsgTopic : delpoyMsgTopic
  serviceMsgTopic : serviceMsgTopic

  # user 가 등록되었을때, cluster 관련 데이터 topic
  stateMsgTopic : stateMsgTopic
  # 각종 처리 완료시 보내오는 상태값 관련 topic
  statusTopic: statusTopic


---
spring:
  profiles: default
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085

api-service-url: http://localhost:8086
---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
#    bootstrap-servers: uengine-kube-kafka:9092
#    bootstrap-servers: my-kafka:9092

api-service-url: http://serviceapi:8080