server:
  port: 8080


topic:
  orderTopic: orderTopic

---
spring:
  profiles: default
  kafka:
    #    bootstrap-servers: http://35.194.123.133:19092
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
  jpa:
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace        

---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      enable-auto-commit: true