server:
  port:
    8081
#  http2:
#    enabled: true
  ssl:
    key-store: keystore.p12
    key-store-password: cheese
    keyStoreType: PKCS12
    keyAlias: tomcat
    enabled: true
  http:
    port:
      8080
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
#  cloud:
#    gcp:
#      projectId: cloud-run-1
#      sql:
#        instanceName: ${CLOUDSQL_INSTANCE}
#        databaseName: ${DBNAME}
#        userName: ${DBUSER}
#        password: ${DBPASS}
  datasource:
    url: jdbc:mysql://google/uengine?cloudSqlInstance=cloud-run-1:us-central1:sh-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&user=root&password=my-secret-pw
    # mybatis 설정시에는 driverClassName 을 넣어주어야함
    username: ${DBUSER}
    password: ${DBPASS}
    #    username: root
    #    password: my-secret-pw
    # mybatis 설정시에는 driverClassName 을 넣어주어야함
    driverClassName: com.mysql.cj.jdbc.Driver

google:
  client:
    clientId: 291986658194-7qh8fnb5bsg0t0gvjghtf2giij23g2es.apps.googleusercontent.com
    clientSecret: oj9gsyMZprsSqQv27ljNg0tL
    accessTokenUri: https://oauth2.googleapis.com/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

---
spring:
  profiles: default

server:
  port: 8080
---
spring:
  profiles: docker


