server:
  port: 8080


topic:
  orderTopic: orderTopic
  stateMsgTopic: stateMsgTopic
  # 각종 처리 완료시 보내오는 상태값 관련 topic
  statusTopic: statusTopic

---
spring:
  profiles: default
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
server:
  port: 8087
---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
#    bootstrap-servers: uengine-kube-kafka:9092
    #    bootstrap-servers: my-kafka:9092
    consumer:
      enable-auto-commit: true
