steps:
  ### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo '$COMMIT_SHA =' $COMMIT_SHA
        docker build -t gcr.io/$PROJECT_ID/$_PROJECT_NAME:$COMMIT_SHA .
  ### Test
  ### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push gcr.io/$PROJECT_ID/$_PROJECT_NAME:$COMMIT_SHA
  ### deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLUSTER=standard-cluster-1
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=asia-northeast1-a
        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"

        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $_PROJECT_NAME
          labels:
            app: $_PROJECT_NAME
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: $_PROJECT_NAME
          template:
            metadata:
              labels:
                app: $_PROJECT_NAME
            spec:
              containers:
                - name: $_PROJECT_NAME
                  image: gcr.io/$PROJECT_ID/$_PROJECT_NAME:$COMMIT_SHA
                  ports:
                    - containerPort: 8080
        EOF
#  - id: 'deploy2'
#    name: 'gcr.io/cloud-builders/kubectl'
#    args:
#      - set
#      - image
#      - deployment
#      - $_PROJECT_NAME
#      - delivery=gcr.io/$PROJECT_ID/$_PROJECT_NAME:$COMMIT_SHA
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'