apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cycle-ingress
  annotations:
    #ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Authentication,access_token,client-key,client-secret,Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Allow-Origin"
spec:
  rules:
    - http:
        paths:
          - path: /kube
            backend:
              serviceName: serviceapi
              servicePort: 8080
          - path: /kubesse
            backend:
              serviceName: serviceapi
              servicePort: 8080
status:
  loadBalancer:
    ingress:
      - hostname: ac919429a22b611e9884d02be6ea23ef-400105267.ap-northeast-2.elb.amazonaws.com