dependencies:
- name: mysql
  version: 0.15.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name:  redis
  version: 6.1.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kafka
  version: 0.13.9
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
