
server:
  port: 8080


#          jwk-set-uri: https://idp.example.com/.well-known/jwks.json

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: as466gf
#        key-value: 123


---
spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: serviceapi
          uri: http://localhost:8086
          predicates:
            - Path=/kube/**
        - id: servicesse
          uri: http://localhost:8086
          predicates:
            - Path=/kubesse/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
              - "null"
              - "localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

---
spring:
  profiles: docker
