
server:
  port: 8080

---
spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: serviceapi
          uri: http://localhost:8086
          predicates:
            - Path=/kube/**
        - id: servicesse
          uri: http://localhost:8086
          predicates:
            - Path=/kubesse/**
        - id: monitor-pod
          uri: http://localhost:8085
          predicates:
            - Path=/api/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: serviceapi
          uri: http://serviceapi:8080
          predicates:
            - Path=/kube/**
        - id: servicesse
          uri: http://serviceapi:8080
          predicates:
            - Path=/kubesse/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
