apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceapi
  labels:
    app: serviceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceapi
  template:
    metadata:
      labels:
        app: serviceapi
    spec:
      containers:
        - name: serviceapi
          image: 979050235289.dkr.ecr.ap-northeast-2.amazonaws.com/uengine/serviceapi