apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-monitor
  labels:
    app: pod-monitor
spec:
  replicas: {{ .Values.monitor.replicas | default 1 }}
  selector:
    matchLabels:
      app: pod-monitor
  template:
    metadata:
      labels:
        app: pod-monitor
    spec:
      containers:
      - name: pod-monitor
        image: {{ .Values.repo }}/pod-monitor
        env:
        - name: kubehost
          value: {{ .Values.kubehost }}
        - name: kubetoken
          value: {{ .Values.kubetoken }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-monitor
  labels:
    app: deploy-monitor
spec:
  replicas: {{ .Values.monitor.replicas | default 1 }}
  selector:
    matchLabels:
      app: deploy-monitor
  template:
    metadata:
      labels:
        app: deploy-monitor
    spec:
      containers:
      - name: deploy-monitor
        image: {{ .Values.repo }}/deploy-monitor
        env:
        - name: kubehost
          value: {{ .Values.kubehost }}
        - name: kubetoken
          value: {{ .Values.kubetoken }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitor
  labels:
    app: service-monitor
spec:
  replicas: {{ .Values.monitor.replicas | default 1 }}
  selector:
    matchLabels:
      app: service-monitor
  template:
    metadata:
      labels:
        app: service-monitor
    spec:
      containers:
      - name: pod-monitor
        image: {{ .Values.repo }}/service-monitor
        env:
        - name: kubehost
          value: {{ .Values.kubehost }}
        - name: kubetoken
          value: {{ .Values.kubetoken }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-kube-controller
  labels:
    app: service-kube-controller
spec:
  replicas: {{ .Values.kubecontroller.replicas | default 1 }}
  selector:
    matchLabels:
      app: service-kube-controller
  template:
    metadata:
      labels:
        app: service-kube-controller
    spec:
      containers:
      - name: service-kube-controller
        image: {{ .Values.repo }}/service-kube-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceapi
  labels:
    app: serviceapi
spec:
  replicas: {{ .Values.serviceapi.replicas | default 1 }}
  selector:
    matchLabels:
      app: serviceapi
  template:
    metadata:
      labels:
        app: serviceapi
    spec:
      containers:
      - name: serviceapi
        image: {{ .Values.repo }}/serviceapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceui
  labels:
    app: serviceui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceui
  template:
    metadata:
      labels:
        app: serviceui
    spec:
      containers:
      - name: serviceui
        image: {{ .Values.repo }}/serviceui
